spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&&serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    port: 6379
    host: localhost

mybatis:
  configuration:
    map-underscore-to-camel-case: true


logging:
  level:
    com.yu.demo: debug
